let map = new Map();
map.set(1,'Francisco');
map.set(2,'Pepe');
map.set(3,'Luis');
map.set(4,'Jose');
map.set(5,'Lalo');
map.set(6,'Lucy');
map.set(7,'Joel');
map.set(8,'Rocio');
map.set(9,'Javi');
map.set(10,'Miranda');
console.log(map);