let weakset=new WeakSet();
console.log("El set es un conjuntos de elementos no repetidos, que pueden ser tanto objetos, como valores primitivos.\n Los WeakSets únicamente pueden contener colecciones de objetos, la referencia a los objetos es débil\n");
console.log("Weakset:");
weakset.add({});
var obj1={name:'obj1'};
var obj2={name:'obj2'};
weakset.add(obj1);
weakset.add(obj2);
obj1=null;
obj2=null;
console.log(weakset);
console.log("\n El weakset a diferencia del set es mas debil, es decir si el obj1 y obj2 dejara de mantener la referencia del objeto, el weakset eventualmente dejaria de tener estos 2 objetos en su estructura de datos");
console.log("\nset:");
let set=new Set();
set.add({});
var obj1={name:'obj1'};
var obj2={name:'obj2'};
set.add(obj1);
set.add(obj2);
obj1=null;
obj2=null;
console.log(set);
console.log("Logramos ver que el set sigue manteniendo los valores");